"""add layout data

Revision ID: 058395293fca
Revises: 0c128e7b04ac

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058395293fca'
down_revision: Union[str, Sequence[str], None] = '0c128e7b04ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_sheet_templates', sa.Column('layout_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_sheet_templates', 'layout_data')
    # ### end Alembic commands ###
